### ISSUE TITLE
Missing human sample: M1_donor2_neun

### ISSUE THREAD

**Issue by gokceneraslan** [UCDNJJ/ucdnjj.github.io#2]
In the human h5ad files, I see 6 samples:

'M1_donor1', 'M1_donor1_neun', 'M1_donor2', 'M1_donor3', 'M1_donor3_neun', 'M1_donor3_rep2'

while in the human ATAC fragment files and RNA BAM files, I see 7 sample names:

'M1_donor1', 'M1_donor1_neun', 'M1_donor2',  'M1_donor2_neun', 'M1_donor3', 'M1_donor3_neun', 'M1_donor3_rep2'

where the difference is the 'M1_donor2_neun' sample. I was just wondering if this is normal and why M1_donor2_neun doesn't exist in the h5ad files.

**Comment by gokceneraslan** [comment]
Not sure it's related but also on the website it says `40,937 human nuclei` while there is `31,960` in the human h5ad files.

**Comment by UCDNJJ** [comment]
Hi @gokceneraslan, for the purposes of this challenge you can feel free to ignore the "M1_donor2_neun" in the fragment / bam files. We didn't quite have that sample ready while building the .h5ad objects. 

However, you are more than welcome to use the M1_donor2_neun data just knowing that the .h5ad object for human doesn't leverage the RNA/ATAC from that sample for the peak calling  and cell type mapping.

**Comment by gokceneraslan** [comment]
Thank you! And the difference between 40k and 31k nuclei?

**Comment by UCDNJJ** [comment]
The difference is due to the website including the "M1_donor2_neun" nuclei counts and potentially some differences in quality control within the .h5ad being shared for the challenge. 

Thanks for catching these discrepancies but we have no plans to update the human .h5ad to include this missing sample. You are more than welcome to for your modeling though!
